/**
 * GitNexus Wiki Integration
 *
 * Reads wiki content generated by `gitnexus wiki` from the repo's
 * `.gitnexus/wiki/` directory. The wiki is generated via CLI once,
 * then served as static markdown by OpenCodeWiki.
 *
 * Wiki output from GitNexus:
 *   {repoRoot}/.gitnexus/wiki/
 *   ├── overview.md          — project overview page
 *   ├── {slug}.md            — module pages
 *   ├── module_tree.json     — navigation structure
 *   ├── meta.json            — generation metadata
 *   └── index.html           — standalone viewer (optional)
 */

import fs from 'fs/promises';
import path from 'path';

/** Module tree node from GitNexus wiki. */
export interface ModuleTreeNode {
  name: string;
  slug: string;
  files: string[];
  children?: ModuleTreeNode[];
}

/** Wiki generation result. */
export interface WikiGenerateResult {
  success: boolean;
  pages?: number;
  output_dir?: string;
  error?: string;
}

/**
 * Generate wiki for a repo by calling `gitnexus wiki`.
 * Returns a promise that resolves when the process exits.
 */
export async function generateWiki(repoPath: string): Promise<WikiGenerateResult> {
  const { spawn } = await import('child_process');
  return new Promise((resolve) => {
    const child = spawn('gitnexus', ['wiki', repoPath], {
      timeout: 600_000,
      cwd: repoPath,
      stdio: ['ignore', 'pipe', 'pipe'] as const,
    });

    let stderr = '';
    child.stderr?.on('data', (chunk: string) => { stderr += chunk; });

    child.on('close', (code: number | null) => {
      if (code === 0) {
        resolve({
          success: true,
          pages: 0,
          output_dir: path.join(repoPath, '.gitnexus', 'wiki'),
        });
      } else {
        resolve({
          success: false,
          error: `gitnexus wiki exited with code ${code}: ${stderr.trim() || 'unknown error'}`,
        });
      }
    });

    child.on('error', (err: Error) => {
      resolve({ success: false, error: `Failed to spawn gitnexus: ${err.message}` });
    });
  });
}

/**
 * Read a specific wiki page by slug (without .md extension).
 * Returns null if the page doesn't exist.
 */
export async function readWikiPage(wikiDir: string, slug: string): Promise<string | null> {
  const safe = path.basename(slug).replace(/\.\./g, '');
  const filePath = path.join(wikiDir, `${safe}.md`);
  if (!filePath.startsWith(path.resolve(wikiDir))) return null;
  try {
    return await fs.readFile(filePath, 'utf-8');
  } catch {
    return null;
  }
}

/** Read the overview page. */
export async function readWikiOverview(wikiDir: string): Promise<string | null> {
  return readWikiPage(wikiDir, 'overview');
}

/** List all wiki page slugs (filenames without .md). */
export async function listWikiPages(wikiDir: string): Promise<string[]> {
  try {
    const entries = await fs.readdir(wikiDir, { withFileTypes: true });
    return entries
      .filter(e => e.isFile() && e.name.endsWith('.md'))
      .map(e => e.name.slice(0, -3))
      .sort();
  } catch {
    return [];
  }
}

/** Load the module tree for navigation sidebar. */
export async function loadModuleTree(wikiDir: string): Promise<ModuleTreeNode[]> {
  try {
    const raw = await fs.readFile(path.join(wikiDir, 'module_tree.json'), 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

/** Default wiki directory for a repo (.codegraph/wiki/). */
export function wikiOutputDir(repoPath: string): string {
  return path.join(repoPath, '.codegraph', 'wiki');
}
